[observatory]
observatory_lat = -29.0146
observatory lon = -70.6926
#from Las Campanas Observatory website

[instrument]
primary_diam = 6.5
secondary_diam = 0.851
#secondary diameter from Close et al 2008

# updated astrometric calibration from Balmer 2021
pixel_scale = 0.006
ifs_rotation = -0.497
# error is ±0.192
ifs_lenslet_scale = 0.00795
# error is ± 0.010 mas per pixel

#these zero points should be calibrated (magnitudes)
zero_pt_flux_HA = 0.0
zero_pt_flux_HACONT = 0.0
zero_pt_flux_zp = 0.0
zero_pt_flux_rp = 0.0
zero_pt_flux_ip = 0.0


cen_wave_HA = 0.656
cen_wave_HACONT = 0.668
cen_wave_zp = 0.909
cen_wave_rp = 0.615
cen_wave_ip = 0.762
cen_wave_gp = 0.527
cen_wave_CH4 = 0.875
cen_wave_CH4CONT = 0.923

#from filter profiles
#fwhm for HA is 0.0046
#fwhm for cont is 0.0061
ghost_ratio_HA = 0.0042
ghost_ratio_CONT = 0.0042
ghost_ratio_i' = 0.001998
ghost_ratio_z' = 0.001220
